car_info = {
    'name': 'toyota camry',
    'type_of_fuel': 100,
    'name_of_fuel': 'premium',
    'drive': '2WD',
    'top_speed': 180,
    'type_top_speed': 'km/h',
    'fuel_consamption': 4.5,
    'engine_type': 'Hybrid',
    'combined_cycle': 103,
    'type_combined_cycle': 'g/km',
    'maximum_power': 218,
    'type_maximum_power': 'hp',
    'working_volume': 2487,
    'type_working_volume': 'centimeters cubed',
    'number_of_cylinder': 4,
    'arrangement_of_cylinders': 'in-line',
    'full_mass': 2100,
    'equipped_mass': '1695-1730',
    'type_of_mass': 'kg',
    'dimensions': {
            'type': 'mm',
            'length': 4885,
            'width': 1840,
            'height': 1445,
            'wheel_base': 2825,
            'front_track_width': 1590,
            'rear_track_width': 1610,
            'overhang_ahead': 975,
            'overhang_behind': 1085,
    },
    'equipment': [
        'auxiliary system',
        'wheels and tires',
        'features of the interior',
        'safety measures',
        'transportail of things',
        'multimedia',
        'comfort',
        'features of the exterior',
    ]
}
